name: emoji_reaction_frontend
description: Flutter web frontend for emoji reaction counter application
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0
  provider: ^6.0.5
  qr_flutter: ^4.1.0
  flutter_animate: ^4.2.0
  url_launcher: ^6.1.12
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
