name: emoji_reaction_frontend
description: Flutter web frontend for emoji reaction counter application
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.3
  provider: ^6.0.5
  qr_flutter: ^4.1.0
  flutter_animate: ^4.2.0
  url_launcher: ^6.1.12
  shared_preferences: ^2.2.0
  logging: ^1.2.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - dotenv
