name: emoji_reaction_backend
description: WebSocket backend for emoji reaction counter application
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_web_socket: ^1.0.4
  shelf_static: ^1.1.2
  web_socket_channel: ^2.4.0
  json_annotation: ^4.8.1
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
