/* This is a simplified version of what would normally be generated by Serverpod */

import 'protocol/emoji_reaction.dart';
import 'protocol/emoji_counts.dart';

class Protocol {
  static final Protocol instance = Protocol();

  final Map<String, Function> _entityDecoders = {};

  Protocol() {
    _entityDecoders['emoji_reaction'] = EmojiReaction.fromJson;
    _entityDecoders['emoji_counts'] = EmojiCounts.fromJson;
  }

  dynamic deserialize(String classId, Map<String, dynamic> json) {
    final deserializer = _entityDecoders[classId];
    if (deserializer == null) {
      throw Exception('No deserializer for $classId');
    }
    return deserializer(json);
  }
}
