name: emoji_reaction_serverpod
description: Serverpod-style implementation of the emoji reaction backend
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
