branch-defaults:
  default:
    environment: emoji-reaction-env
    group_suffix: null
global:
  application_name: emoji-reaction-app
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
